/* ================================================================
   種目データベース(確定版 48種目 / 番号は絶対に振り直さない)
   goals: agility(敏捷性) / defense(ディフェンス) / cutman(カットマン) /
          speed(球速アップ) / attack(アタック) / power(パワー・瞬発力・全身パワーを含む) /
          stamina(スタミナ) / core(体幹)
   space: point(その場) < small(1畳) < medium(1〜2畳/2畳) < wide(広め)
   quiet: 'quiet'(○静音) / 'some'(△少しならOK) / 'loud'(×気にしない向け)
   difficultyLevel: 1=初級 / 2=中級 / 3=上級(その難易度"まで"を許容するフィルターに使用)
   pairLR: true の種目はメニュー採用時に右→左で2枠を消費する
   ================================================================ */

const SPACE_ORDER = { point: 0, small: 1, medium: 2, wide: 3 };
const DIFFICULTY_LEVEL = { beginner: 1, intermediate: 2, advanced: 3 };
const QUIET_ORDER = { quiet: 0, some: 1, loud: 2 };

const EXERCISES = [
  // ---------- A. フットワーク・敏捷性(1-12) ----------
  { id: "1-side-step", no: 1, name: "サイドステップ", category: "footwork", baseIntensity: "medium",
    goals: ["defense", "cutman", "agility", "stamina"], space: "small", jump: false, quiet: "quiet",
    difficultyLevel: 1, pairLR: false, image: "images/exercises/1-side-step.jpg",
    description: "左右に素早く移動する基本の動き。",
    points: ["膝を軽く曲げて、低い姿勢を保つ", "足を大きく交差させない", "リズムよく、左右に素早く動く"] },
  { id: "2-back-step", no: 2, name: "バックステップ", category: "footwork", baseIntensity: "medium",
    goals: ["defense", "cutman", "agility"], space: "small", jump: false, quiet: "quiet",
    difficultyLevel: 1, pairLR: false, image: "images/exercises/2-back-step.jpg",
    description: "後ろに素早く下がる基本の動き。",
    points: ["膝を軽く曲げて、低い姿勢を保つ", "上半身は前を向いたまま、素早く後ろに下がる", "かかとから静かに下がり、バランスを崩さない"] },
  { id: "3-front-back-step", no: 3, name: "前後ステップ", category: "footwork", baseIntensity: "medium",
    goals: ["defense", "cutman", "agility", "stamina"], space: "small", jump: false, quiet: "quiet",
    difficultyLevel: 1, pairLR: false, image: "images/exercises/3-front-back-step.jpg",
    description: "前後に素早く移動する基本の動き。",
    points: ["膝を軽く曲げて、低い姿勢を保つ", "大きく動かず、素早く前後に移動する", "上半身は前を向いたまま、バランスを崩さない"] },
  { id: "4-in-out-step", no: 4, name: "イン・アウトステップ", category: "footwork", baseIntensity: "medium",
    goals: ["agility", "defense", "cutman"], space: "small", jump: false, quiet: "quiet",
    difficultyLevel: 2, pairLR: false, image: "images/exercises/4-in-out-step.jpg",
    description: "ラダーを使ったように足を素早く入れ替える動き(その場でできる)。",
    points: ["膝を軽く曲げて、低い姿勢を保つ", "イン・アウトのリズムで素早く動く", "足を大きく上げすぎず、つま先で素早く入れ替える"] },
  { id: "5-split-step", no: 5, name: "スプリットステップ", category: "footwork", baseIntensity: "medium",
    goals: ["defense", "cutman", "agility"], space: "point", jump: false, quiet: "quiet",
    difficultyLevel: 2, pairLR: false, image: "images/exercises/5-split-step.jpg",
    description: "相手の動きに反応するために一瞬で踏み替える基本の動き。",
    points: ["両足で軽く跳び、素早く着地する", "着地と同時に次の動き(左右・前後)に移れるようにする", "膝を軽く曲げて、低い姿勢を保つ"] },
  { id: "6-cross-step", no: 6, name: "クロスステップ", category: "footwork", baseIntensity: "medium",
    goals: ["cutman", "agility", "defense"], space: "small", jump: false, quiet: "quiet",
    difficultyLevel: 2, pairLR: false, image: "images/exercises/6-cross-step.jpg",
    description: "足を交差させながら素早く横に移動する動き。",
    points: ["後ろの足を前の足の前に交差させる", "交差した足で素早く横に移動し、次の足を出す", "左右どちらの方向にもできる"] },
  { id: "7-lateral-step", no: 7, name: "ラテラルステップ", category: "footwork", baseIntensity: "medium",
    goals: ["defense", "cutman", "agility"], space: "small", jump: false, quiet: "quiet",
    difficultyLevel: 1, pairLR: false, image: "images/exercises/7-lateral-step.jpg",
    description: "サイドステップより大きく横方向に移動する動き。",
    points: ["サイドステップより大きく、横方向へ移動する動き", "足を大きく開きすぎない(肩幅〜1.5倍程度)", "つま先は進行方向に向ける"] },
  { id: "8-skater-step", no: 8, name: "スケーターステップ", category: "footwork", baseIntensity: "medium",
    goals: ["cutman", "agility", "power"], space: "medium", jump: false, quiet: "quiet",
    difficultyLevel: 2, pairLR: false, image: "images/exercises/8-skater-step.jpg",
    description: "左右にジャンプしながら横方向へ移動する動き。",
    points: ["片足で横にジャンプし、反対側の足で着地する", "片足で着地し、バランスを保つ", "左右どちらの方向にもできる"] },
  { id: "9-quick-feet-small", no: 9, name: "その場細かい足踏み", category: "footwork", baseIntensity: "low",
    goals: ["stamina", "agility", "defense"], space: "point", jump: false, quiet: "quiet",
    difficultyLevel: 1, pairLR: false, image: "images/exercises/9-quick-feet-small.jpg",
    description: "その場で小さく・速く足を動かす動き(基本版)。",
    points: ["足は大きく上げず、小さく・速く動かす", "つま先で軽く接地し、かかとをつけない", "リズムよく連続して行う"] },
  { id: "10-shuffle", no: 10, name: "その場シャッフル", category: "footwork", baseIntensity: "medium",
    goals: ["stamina", "agility", "defense"], space: "point", jump: false, quiet: "quiet",
    difficultyLevel: 1, pairLR: false, image: "images/exercises/10-shuffle.jpg",
    description: "その場で素早く前後に足を入れ替える動き。",
    points: ["つま先で軽く着地し、かかとをつかない", "膝を軽く曲げて、低い姿勢を保つ", "リズムよく素早く繰り返す"] },
  { id: "11-quick-feet", no: 11, name: "クイックフィート", category: "footwork", baseIntensity: "high",
    goals: ["agility", "stamina", "defense"], space: "point", jump: false, quiet: "quiet",
    difficultyLevel: 2, pairLR: false, image: "images/exercises/11-quick-feet.jpg",
    description: "その場細かい足踏みの高速版。できるだけ速く足を入れ替える。",
    points: ["つま先で素早く接地し、かかとをつけない", "足の接地時間を短く、リズムよく動かす", "素早く連続して行う"] },
  { id: "12-quick-feet-stop", no: 12, name: "クイックフィート＋ストップ", category: "footwork", baseIntensity: "high",
    goals: ["agility", "defense", "cutman"], space: "small", jump: false, quiet: "quiet",
    difficultyLevel: 2, pairLR: false, image: "images/exercises/12-quick-feet-stop.jpg",
    description: "その場で素早く足を動かし、合図でピタッと止まる動き。",
    points: ["小さく・速く足を入れ替え、つま先で軽く接地する", "止まるときは姿勢を崩さず、膝を軽く曲げたまま止まる", "反応力・瞬発力・体のコントロールを鍛える"] },

  // ---------- B. 下半身・片脚(13-22) ----------
  { id: "13-squat", no: 13, name: "スクワット", category: "lower", baseIntensity: "medium",
    goals: ["power", "stamina", "attack", "speed"], space: "point", jump: false, quiet: "quiet",
    difficultyLevel: 1, pairLR: false, image: "images/exercises/13-squat.jpg",
    description: "足を肩幅に開き、しゃがんで立ち上がる基本の下半身種目。",
    points: ["背すじを伸ばし、胸を張る", "膝がつま先より前に出ない", "かかとをつけたまま行う"] },
  { id: "14-reverse-lunge", no: 14, name: "リバースランジ", category: "lower", baseIntensity: "medium",
    goals: ["power", "attack", "speed", "core"], space: "small", jump: false, quiet: "quiet",
    difficultyLevel: 1, pairLR: false, image: "images/exercises/14-reverse-lunge.jpg",
    description: "片足を後ろに下げて腰を落とす。",
    points: ["上半身はまっすぐ", "前の膝がつま先より前に出ない", "左右交互に行う"] },
  { id: "15-forward-lunge", no: 15, name: "フォワードランジ", category: "lower", baseIntensity: "medium",
    goals: ["power", "attack", "speed", "core"], space: "small", jump: false, quiet: "quiet",
    difficultyLevel: 1, pairLR: false, image: "images/exercises/15-forward-lunge.jpg",
    description: "片足を前に踏み出して腰を落とす。",
    points: ["上半身はまっすぐ", "前の膝がつま先より前に出ない", "左右交互に行う"] },
  { id: "16-side-lunge", no: 16, name: "サイドランジ", category: "lower", baseIntensity: "medium",
    goals: ["defense", "cutman", "power", "agility"], space: "small", jump: false, quiet: "quiet",
    difficultyLevel: 1, pairLR: false, image: "images/exercises/16-side-lunge.jpg",
    description: "横に大きく踏み出して腰を落とす。",
    points: ["膝がつま先より前に出ない", "踏み出した足のつま先と膝を同じ方向に", "左右交互に行う"] },
  { id: "17-single-leg-squat", no: 17, name: "シングルレッグスクワット", category: "lower", baseIntensity: "high",
    goals: ["power", "agility", "core", "speed"], space: "point", jump: false, quiet: "quiet",
    difficultyLevel: 3, pairLR: true, image: "images/exercises/17-single-leg-squat.jpg",
    description: "片脚立ちで浅くしゃがむバランス種目。",
    points: ["上半身はまっすぐ", "支えている足の膝がつま先より前に出ない", "バランスを保ちながら、ゆっくり行う"] },
  { id: "18-calf-raise", no: 18, name: "カーフレイズ", category: "lower", baseIntensity: "low",
    goals: ["agility", "power", "stamina"], space: "point", jump: false, quiet: "quiet",
    difficultyLevel: 1, pairLR: false, image: "images/exercises/18-calf-raise.jpg",
    description: "つま先立ちでかかとを上げ下げする。",
    points: ["上半身はまっすぐ", "つま先でしっかり地面を押す", "かかとを高く上げて、ゆっくり下ろす"] },
  { id: "19-single-calf-raise", no: 19, name: "シングルレッグカーフレイズ", category: "lower", baseIntensity: "medium",
    goals: ["agility", "power", "core"], space: "point", jump: false, quiet: "quiet",
    difficultyLevel: 2, pairLR: true, image: "images/exercises/19-single-calf-raise.jpg",
    description: "片足でかかとを上げ下げする。",
    points: ["上半身はまっすぐ", "つま先でしっかり地面を押す", "左右交互に行う"] },
  { id: "20-hip-lift", no: 20, name: "ヒップリフト", category: "lower", baseIntensity: "low",
    goals: ["core", "power", "speed", "attack"], space: "small", jump: false, quiet: "quiet",
    difficultyLevel: 1, pairLR: false, image: "images/exercises/20-hip-lift.jpg",
    description: "仰向けでお尻を持ち上げる。",
    points: ["肩から膝までが一直線になるように上げる", "お腹とお尻に力を入れる", "腰を反らせすぎない"] },
  { id: "21-single-hip-lift", no: 21, name: "シングルレッグヒップリフト", category: "lower", baseIntensity: "medium",
    goals: ["core", "power", "speed", "attack"], space: "small", jump: false, quiet: "quiet",
    difficultyLevel: 2, pairLR: true, image: "images/exercises/21-single-hip-lift.jpg",
    description: "片脚を上げたままお尻を持ち上げる。",
    points: ["肩から膝までが一直線になるように上げる", "腰を反らせすぎない", "左右交互に行う"] },
  { id: "22-single-hop-arm-swing", no: 22, name: "片脚ホップ＋腕振り", category: "lower", baseIntensity: "high",
    goals: ["cutman", "agility", "power", "attack"], space: "small", jump: false, quiet: "some",
    difficultyLevel: 2, pairLR: true, image: "images/exercises/22-single-hop-arm-swing.jpg",
    description: "片足でリズミカルに連続でホップしながら腕を振る。",
    points: ["つま先で軽く地面を押して跳ぶ", "腕を前後に大きく振る", "左右交互に行う"] },

  // ---------- C. ジャンプ・瞬発力(23-32) ----------
  { id: "23-jump-squat", no: 23, name: "ジャンプスクワット", category: "jump", baseIntensity: "high",
    goals: ["power", "attack", "speed", "stamina"], space: "small", jump: true, quiet: "loud",
    difficultyLevel: 2, pairLR: false, image: "images/exercises/23-jump-squat.jpg",
    description: "しゃがんでから腕を振って真上にジャンプする。",
    points: ["膝はつま先と同じ向きに保つ", "着地はつま先から、膝を軽く曲げる", "連続してリズムよく行う"] },
  { id: "24-lunge-jump", no: 24, name: "ランジジャンプ", category: "jump", baseIntensity: "high",
    goals: ["power", "attack", "agility"], space: "medium", jump: true, quiet: "loud",
    difficultyLevel: 3, pairLR: false, image: "images/exercises/24-lunge-jump.jpg",
    description: "ランジの姿勢からジャンプして前後の脚を入れ替える。",
    points: ["前後の足を素早く入れ替える", "上半身はまっすぐ、体幹を安定させる", "着地はつま先から、膝を軽く曲げる"] },
  { id: "25-side-jump", no: 25, name: "サイドジャンプ", category: "jump", baseIntensity: "high",
    goals: ["cutman", "agility", "power", "defense"], space: "medium", jump: true, quiet: "loud",
    difficultyLevel: 2, pairLR: false, image: "images/exercises/25-side-jump.jpg",
    description: "左右にジャンプして移動する。",
    points: ["膝を軽く曲げて、低い姿勢で行う", "つま先で素早く左右に跳ぶ", "上半身はぶらさず、バランスを保つ"] },
  { id: "26-skater-jump", no: 26, name: "スケータージャンプ", category: "jump", baseIntensity: "high",
    goals: ["cutman", "agility", "power"], space: "medium", jump: true, quiet: "loud",
    difficultyLevel: 3, pairLR: false, image: "images/exercises/26-skater-jump.jpg",
    description: "斜め後ろに大きく跳び、片足で着地して反対側へ切り返す。",
    points: ["斜め後ろに大きく跳び、片足で着地", "着地時に膝をしっかり曲げ、バランスを保つ", "左右交互に行う"] },
  { id: "27-front-back-jump", no: 27, name: "前後ジャンプ", category: "jump", baseIntensity: "high",
    goals: ["cutman", "agility", "power"], space: "medium", jump: true, quiet: "loud",
    difficultyLevel: 2, pairLR: false, image: "images/exercises/27-front-back-jump.jpg",
    description: "前後に素早くジャンプする(その場で往復)。",
    points: ["つま先で軽く着地し、膝を柔らかく使う", "上半身はまっすぐ、バランスを保つ", "リズムよく連続して行う"] },
  { id: "28-small-jumps", no: 28, name: "連続小ジャンプ", category: "jump", baseIntensity: "medium",
    goals: ["agility", "stamina", "power"], space: "point", jump: true, quiet: "loud",
    difficultyLevel: 1, pairLR: false, image: "images/exercises/28-small-jumps.jpg",
    description: "その場で小さく連続ジャンプする。",
    points: ["つま先で連続して小さく跳ぶ", "かかとをつけず、リズムよく行う", "上半身はまっすぐ、力を抜いて跳ぶ"] },
  { id: "29-tuck-jump", no: 29, name: "タックジャンプ", category: "jump", baseIntensity: "high",
    goals: ["power", "stamina"], space: "small", jump: true, quiet: "loud",
    difficultyLevel: 3, pairLR: false, image: "images/exercises/29-tuck-jump.jpg",
    description: "腕を振って真上にジャンプし、膝を胸に引き上げる。",
    points: ["高く跳び、膝を胸に引き上げる", "腕を使ってジャンプの高さを出す", "着地はつま先から、膝を軽く曲げる"] },
  { id: "30-jumping-jack", no: 30, name: "ジャンピングジャック", category: "jump", baseIntensity: "medium",
    goals: ["stamina", "agility", "power"], space: "small", jump: true, quiet: "loud",
    difficultyLevel: 1, pairLR: false, image: "images/exercises/30-jumping-jack.jpg",
    description: "手足を開閉しながらジャンプする。",
    points: ["足を開くと同時に腕を大きく振り上げる", "リズミカルに全身を動かす", "着地はつま先から、膝を軽く曲げる"] },
  { id: "31-split-jump", no: 31, name: "スプリットジャンプ", category: "jump", baseIntensity: "high",
    goals: ["power", "attack", "agility"], space: "medium", jump: true, quiet: "loud",
    difficultyLevel: 3, pairLR: false, image: "images/exercises/31-split-jump.jpg",
    description: "前後に足を開いたランジの姿勢から真上に高く跳び、空中で足を入れ替える。",
    points: ["その場で真上に高く跳び、空中で足を入れ替える", "上半身はまっすぐ、体幹を安定させる", "着地はつま先から、膝を軽く曲げる", "ランジジャンプより滞空時間を長く、より高く跳ぶ"] },
  { id: "32-single-hop-arm-swing", no: 32, name: "片脚ホップ＋腕振り", category: "jump", baseIntensity: "high",
    goals: ["cutman", "agility", "power", "attack"], space: "small", jump: true, quiet: "loud",
    difficultyLevel: 2, pairLR: true, image: "images/exercises/32-single-hop-arm-swing.jpg",
    description: "片足でリズミカルに連続でホップしながら腕を大きく振る(ジャンプ版)。",
    points: ["つま先で軽く地面を押して跳ぶ", "腕を前後に大きく振る", "上半身はまっすぐ、リズムよく続ける", "左右交互に行う"] },

  // ---------- D. 心肺・全身(33-41、スクワットスラストは削除済み) ----------
  { id: "33-high-knees", no: 33, name: "ハイニー", category: "cardio", baseIntensity: "high",
    goals: ["stamina", "agility", "power"], space: "point", jump: false, quiet: "some",
    difficultyLevel: 1, pairLR: false, image: "images/exercises/33-high-knees.jpg",
    description: "背筋を伸ばして立ち、片膝を高く上げて交互に行う。",
    points: ["膝を高く上げて、リズムよく行う", "つま先で接地し、かかとをつかない", "上半身はまっすぐ、腕をしっかり振る", "20〜30秒など、一定時間続ける"] },
  { id: "34-running-in-place", no: 34, name: "その場ランニング", category: "cardio", baseIntensity: "medium",
    goals: ["stamina", "agility"], space: "point", jump: false, quiet: "some",
    difficultyLevel: 1, pairLR: false, image: "images/exercises/34-running-in-place.jpg",
    description: "背筋を伸ばして立ち、その場で足を素早く入れ替えて走る。",
    points: ["その場で素早く足を動かす", "つま先で軽く接地し、かかとをつかない", "腕をしっかり振る", "20〜30秒など、一定時間続ける"] },
  { id: "35-butt-kick", no: 35, name: "バットキック", category: "cardio", baseIntensity: "medium",
    goals: ["stamina", "agility"], space: "point", jump: false, quiet: "some",
    difficultyLevel: 1, pairLR: false, image: "images/exercises/35-butt-kick.jpg",
    description: "かかとをお尻に近づけるように引き上げ、左右交互に行う。",
    points: ["かかとをお尻に近づけるように引き上げる", "上半身はまっすぐ、前に倒さない", "腕をしっかり振る", "20〜30秒など、一定時間続ける"] },
  { id: "36-burpee", no: 36, name: "バーピー", category: "cardio", baseIntensity: "high",
    goals: ["stamina", "power", "agility"], space: "small", jump: false, quiet: "loud",
    difficultyLevel: 2, pairLR: false, image: "images/exercises/36-burpee.jpg",
    description: "立つ→しゃがんで脚を後ろに伸ばす→戻って立つを繰り返す全身種目。",
    points: ["全身を使って素早く行う", "背中をまっすぐに保つ", "動作を止めずにリズムよく続ける", "5〜15回など、一定回数行う"] },
  { id: "37-burpee-jump", no: 37, name: "バーピージャンプ", category: "cardio", baseIntensity: "high",
    goals: ["stamina", "power", "agility"], space: "small", jump: false, quiet: "loud",
    difficultyLevel: 3, pairLR: false, image: "images/exercises/37-burpee-jump.jpg",
    description: "バーピーの最後にジャンプを加えた動き。",
    points: ["バーピーにジャンプを加えた動き", "全身を使って素早く行う", "できるだけ高く跳ぶ", "5〜15回など、一定回数行う"] },
  { id: "38-mountain-climber", no: 38, name: "マウンテンクライマー", category: "cardio", baseIntensity: "high",
    goals: ["stamina", "core", "power"], space: "small", jump: false, quiet: "some",
    difficultyLevel: 2, pairLR: false, image: "images/exercises/38-mountain-climber.jpg",
    description: "腕立ての姿勢で、片膝ずつ交互に胸へ引き寄せる。",
    points: ["腕立ての姿勢で、足を素早く入れ替える", "両手は肩の下につき、背中をまっすぐ保つ", "膝を胸に引き寄せる", "20〜30秒など、一定時間続ける"] },
  { id: "39-bear-crawl", no: 39, name: "ベアクロール", category: "cardio", baseIntensity: "medium",
    goals: ["core", "stamina", "agility"], space: "medium", jump: false, quiet: "quiet",
    difficultyLevel: 2, pairLR: false, image: "images/exercises/39-bear-crawl.jpg",
    description: "四つん這いの姿勢(膝を浮かせる)で前後に移動する。",
    points: ["膝を床につけず、腰をやや低く保つ", "手足を交互に動かして前に進む", "決めた距離を進み、同じ姿勢で戻る", "5〜10mなど、往復で行う"] },
  { id: "40-bear-position-step", no: 40, name: "ベアポジション足踏み", category: "cardio", baseIntensity: "medium",
    goals: ["core", "stamina", "agility"], space: "small", jump: false, quiet: "quiet",
    difficultyLevel: 2, pairLR: false, image: "images/exercises/40-bear-position-step.jpg",
    description: "四つん這いの姿勢(膝を浮かせる)のまま足踏みする。",
    points: ["膝を床につけず、腰をやや低く保つ", "その場で足を素早く入れ替える", "背中をまっすぐに保つ", "20〜30秒など、一定時間続ける"] },
  { id: "41-sprawl", no: 41, name: "スプロール", category: "cardio", baseIntensity: "high",
    goals: ["stamina", "agility", "power"], space: "medium", jump: false, quiet: "some",
    difficultyLevel: 2, pairLR: false, image: "images/exercises/41-sprawl.jpg",
    description: "立った姿勢からしゃがんで両手をつき、両脚を後ろに伸ばしてすぐ戻る。",
    points: ["立った姿勢から素早く地面に下りる動き", "両手をついて両脚を後ろに伸ばし、すぐに戻って立つ", "膝を床につけない", "5〜15回など、一定回数行う"] },

  // ---------- E. 上半身・体幹(42-48) ----------
  { id: "42-pushup", no: 42, name: "プッシュアップ", category: "core", baseIntensity: "medium",
    goals: ["power", "attack", "speed", "core"], space: "small", jump: false, quiet: "quiet",
    difficultyLevel: 1, pairLR: false, image: "images/exercises/42-pushup.jpg",
    description: "腕を肩幅よりやや広くつき、肘を曲げて胸を床に近づける腕立て伏せ。",
    points: ["頭からかかとまで一直線を保つ", "肘を外に開きすぎない(45度程度)", "胸を床に近づけてからしっかり押し上げる", "10〜20回など、一定回数行う"] },
  { id: "43-knee-pushup", no: 43, name: "膝つきプッシュアップ", category: "core", baseIntensity: "low",
    goals: ["power", "attack", "speed", "core"], space: "small", jump: false, quiet: "quiet",
    difficultyLevel: 1, pairLR: false, image: "images/exercises/43-knee-pushup.jpg",
    description: "膝をついて行う腕立て伏せ。",
    points: ["頭から膝まで一直線を保つ", "肘を外に開きすぎない", "胸を床に近づけてから押し上げる", "通常のプッシュアップが難しい場合に行う"] },
  { id: "44-plank", no: 44, name: "プランク", category: "core", baseIntensity: "low",
    goals: ["core", "speed", "attack"], space: "small", jump: false, quiet: "quiet",
    difficultyLevel: 1, pairLR: false, image: "images/exercises/44-plank.jpg",
    description: "うつ伏せから前腕とつま先で体を支え、その姿勢をキープする。",
    points: ["頭からかかとまで一直線を保つ", "お腹に力を入れて腰が反らないようにする", "呼吸を止めず、リラックスして行う", "20〜60秒など、一定時間キープする"] },
  { id: "45-side-plank", no: 45, name: "サイドプランク", category: "core", baseIntensity: "medium",
    goals: ["core", "defense", "speed"], space: "small", jump: false, quiet: "quiet",
    difficultyLevel: 2, pairLR: true, image: "images/exercises/45-side-plank.jpg",
    description: "横向きに寝て片方の前腕と足の外側で体を支え、その姿勢をキープする。",
    points: ["頭からかかとまで一直線を保つ", "腰が落ちたり上がりすぎないようにする", "体幹を意識して、呼吸を止めずに行う", "左右それぞれ20〜40秒などキープする"] },
  { id: "46-plank-jack", no: 46, name: "プランクジャック", category: "core", baseIntensity: "high",
    goals: ["core", "stamina", "agility"], space: "small", jump: false, quiet: "some",
    difficultyLevel: 2, pairLR: false, image: "images/exercises/46-plank-jack.jpg",
    description: "プランクの姿勢のまま、両足を左右に開閉する(ジャンプしない)。",
    points: ["頭からかかとまで一直線を保つ", "腰が上下しないようにする", "つま先で滑らせるように足を開閉する", "20〜30回など、一定回数行う"] },
  { id: "47-bird-dog", no: 47, name: "バードドッグ", category: "core", baseIntensity: "low",
    goals: ["core", "agility", "speed"], space: "small", jump: false, quiet: "quiet",
    difficultyLevel: 1, pairLR: false, image: "images/exercises/47-bird-dog.jpg",
    description: "四つん這いの姿勢から、片腕と反対側の脚をまっすぐ伸ばす。",
    points: ["腰が反らないように、体幹を安定させる", "背中をまっすぐに保つ", "伸ばした手足は床と平行になるようにする", "左右それぞれ10〜15回など、一定回数行う"] },
  { id: "48-dead-bug", no: 48, name: "デッドバグ", category: "core", baseIntensity: "low",
    goals: ["core", "speed", "attack"], space: "small", jump: false, quiet: "quiet",
    difficultyLevel: 1, pairLR: false, image: "images/exercises/48-dead-bug.jpg",
    description: "仰向けで両手両脚を天井に伸ばし、対角の手脚をゆっくり伸ばす。",
    points: ["腰が反らないように、腰を床に押しつける", "ゆっくりとコントロールして動かす", "呼吸を止めずに行う", "左右それぞれ10〜15回など、一定回数行う"] },
];

// 22と32は同一動作。同一セッションでの重複採用を避ける対の関係。
const EXCLUSIVE_PAIRS = [["22-single-hop-arm-swing", "32-single-hop-arm-swing"]];

// 目的(goals)の日本語ラベル
const GOAL_LABELS = {
  agility: "敏捷性", defense: "ディフェンス", cutman: "カットマン",
  speed: "球速アップ", attack: "アタック", power: "パワー",
  stamina: "スタミナ", core: "体幹",
};

const CATEGORY_LABELS = {
  footwork: "フットワーク", lower: "下半身", jump: "ジャンプ",
  cardio: "カーディオ", core: "体幹",
};

const INTENSITY_LABELS = { low: "低", medium: "中", high: "高" };
const DIFFICULTY_LABELS = { 1: "初級", 2: "中級", 3: "上級" };
